before_build:
- pwsh: dotnet restore
build_script:
- pwsh: dotnet publish -f netcoreapp3.1 -c:Release
- pwsh: dotnet publish -f netstandard2.0 -c:Release OffregLib
- pwsh: dotnet publish -f netstandard2.1 -c:Release OffregLib
after_build:
- dotnet pack -p:PackageId=OffregLib.Forked -o:OffregLib/bin/publish -c:Release OffregLib
artifacts:
- path: OffregLib/bin/publish/*.nupkg
  name: Nuget
- path: OffregLib/bin/Release/netstandard2.0/publish
  name: netstandard2.0
- path: OffregLib/bin/Release/netstandard2.1/publish
  name: netstandard2.1
- path: OffregLib/bin/Release/netcoreapp3.1/publish
  name: netcoreapp3.1
